### PR TITLE
phtal support

### PR DESCRIPTION
**Pull request by jam01**
Hey Mike, here's a first stab at support for phtal. Feel free to ignore it for now. with-rel and with-form should work. I'll create a quick server with some canned responses to test this.

Fixed some trivial things in hal and siren while looking at how they're implemented.

### CODE REVIEW

**Comment by mamund** [comment]
thanks for the bug fixes andk yes, happy to see you working on a PHTAL plugin. i'll wait until you say it's ready for review to merge it in.

#thanks.

**Comment by mamund** [comment]
@jam01 

what's the status of this PR? is it in good enough shape to merge in?

**Comment by jam01** [comment]
it should actually be good, just been taking too long setting up a live service somewhere for anyone to test

**Comment by mamund** [comment]
OK, @jam01 

please mark this "ready for review" and I'll queue it up for a final run through before committing the PR.

once you get a service up and running, please write one or more entiries in the `/scripts` folder to play the role of test/example cases for us to reference.

thanks for your contribution and looking forward to seeing some scripts here soon.

cheers.

**Pull request merged**
